<?php
/**
 * Integration tests for the WXR importer, the relation-resolution pass, and the cleaner —
 * run against a real WordPress install via wp-env (see phpunit.xml.dist / tests/bootstrap.php).
 *
 * @package Tanbiuti
 */

/**
 * Class Tanbiuti_Importer_Test.
 */
class Tanbiuti_Importer_Test extends WP_UnitTestCase {

	/**
	 * Path to the small, hand-built fixture (2 clientes, 1 comanda, 1 recibo, 1 agendamento)
	 * generated by
	 * tools/wxr-builder/scripts/build-test-fixture.ts.
	 *
	 * @var string
	 */
	private $fixture_path;

	/**
	 * Sets up the fixture path and makes sure the post types this test relies on are registered
	 * (they normally are, via the `init` hook, but tests don't always run a full request cycle).
	 */
	public function set_up() {
		parent::set_up();
		$this->fixture_path = __DIR__ . '/fixtures/sample.xml';
		Tanbiuti_CPT_Registrar::register();
		Tanbiuti_Taxonomy_Registrar::register();
	}

	/**
	 * The plugin's post types should all be registered.
	 */
	public function test_registers_all_post_types() {
		foreach ( Tanbiuti_CPT_Registrar::POST_TYPES as $post_type ) {
			$this->assertTrue( post_type_exists( $post_type ), "Post type {$post_type} should be registered." );
		}
	}

	/**
	 * Importing the fixture creates exactly the posts it describes.
	 */
	public function test_import_creates_expected_posts() {
		$result = Tanbiuti_Importer::import_file( $this->fixture_path );

		$this->assertSame( 5, $result['created'] );
		$this->assertSame( 0, $result['updated'] );
		$this->assertSame( 5, $this->count_tanbiuti_posts() );
	}

	/**
	 * The importer's second pass resolves `_tanbiuti_*_source_id` meta into real post ids, so
	 * relations survive across whatever order the WXR items happened to be in.
	 */
	public function test_resolves_relations_between_posts() {
		Tanbiuti_Importer::import_file( $this->fixture_path );

		$comanda      = $this->find_post_by_source_id( 'tanbiuti_comanda', 100 );
		$recibo       = $this->find_post_by_source_id( 'tanbiuti_recibo', 1000 );
		$cliente      = $this->find_post_by_source_id( 'tanbiuti_cliente', 1 );
		$agendamento  = $this->find_post_by_source_id( 'tanbiuti_agendamento', 10000 );

		$this->assertNotNull( $comanda );
		$this->assertNotNull( $recibo );
		$this->assertNotNull( $cliente );
		$this->assertNotNull( $agendamento );

		$this->assertSame( $cliente->ID, (int) get_post_meta( $comanda->ID, '_tanbiuti_cliente_post_id', true ) );
		$this->assertSame( $comanda->ID, (int) get_post_meta( $recibo->ID, '_tanbiuti_comanda_post_id', true ) );
		$this->assertSame( $cliente->ID, (int) get_post_meta( $agendamento->ID, '_tanbiuti_cliente_post_id', true ) );
		$this->assertSame( $comanda->ID, (int) get_post_meta( $agendamento->ID, '_tanbiuti_comanda_post_id', true ) );
	}

	/**
	 * Re-importing the same file updates the existing posts instead of duplicating them.
	 */
	public function test_reimport_is_idempotent() {
		Tanbiuti_Importer::import_file( $this->fixture_path );
		$result = Tanbiuti_Importer::import_file( $this->fixture_path );

		$this->assertSame( 0, $result['created'] );
		$this->assertSame( 5, $result['updated'] );
		$this->assertSame( 5, $this->count_tanbiuti_posts() );
	}

	/**
	 * The cleaner removes every imported post and nothing else, and a subsequent import starts
	 * fresh (creates, rather than updates).
	 */
	public function test_clean_then_reimport_creates_fresh_posts() {
		Tanbiuti_Importer::import_file( $this->fixture_path );

		$other_post_id = self::factory()->post->create( array( 'post_type' => 'post' ) );

		$deleted = Tanbiuti_Cleaner::clean();

		$this->assertSame( 5, $deleted );
		$this->assertSame( 0, $this->count_tanbiuti_posts() );
		$this->assertInstanceOf( WP_Post::class, get_post( $other_post_id ), 'Unrelated posts must survive cleanup.' );

		$result = Tanbiuti_Importer::import_file( $this->fixture_path );
		$this->assertSame( 5, $result['created'] );
	}

	/**
	 * Counts posts across every Tanbiuti post type, regardless of status.
	 *
	 * @return int
	 */
	private function count_tanbiuti_posts() {
		$query = new WP_Query(
			array(
				'post_type'      => array_values( Tanbiuti_CPT_Registrar::POST_TYPES ),
				'post_status'    => 'any',
				'fields'         => 'ids',
				'posts_per_page' => -1,
				'no_found_rows'  => true,
			)
		);
		return count( $query->posts );
	}

	/**
	 * Finds a post by post type and `_tanbiuti_source_id`.
	 *
	 * @param string $post_type Post type to search.
	 * @param int    $source_id Source id to match.
	 * @return WP_Post|null
	 */
	private function find_post_by_source_id( $post_type, $source_id ) {
		$posts = get_posts(
			array(
				'post_type'      => $post_type,
				'post_status'    => 'any',
				'meta_key'       => Tanbiuti_Importer::SOURCE_ID_META,
				'meta_value'     => (string) $source_id,
				'posts_per_page' => 1,
				'no_found_rows'  => true,
			)
		);
		return $posts ? $posts[0] : null;
	}
}
